project:
  type: website

website:
  title: "R/Pharma Summits 2026"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "Discussions"
        href: https://github.com/rinpharma/rinpharma-summit-2026/discussions
      - text: "Past Summaries"
        href: https://rinpharma.com/docs/summit/
      - text: "rinpharma.com"
        href: https://rinpharma.com/
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
